name: Create Binaries JSON

permissions:
  packages: read
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      chain_id:
        description: 'Chain ID (nvnm-1 or nvnm-testnet-1)'
        required: true
        type: choice
        options:
          - nvnm-1
          - nvnm-testnet-1
      tag:
        description: 'Release tag (e.g v1.1.0)'
        required: true
      checksums_url:
        description: 'URL to checksums file (optional)'
        required: false
      upgrade_version:
        description: 'Upgrade version (e.g v2) default to major version of tag if not provided'
        required: false

jobs:
  create-binaries-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r scripts/create_binaries_json/requirements.txt

      - name: Create binaries JSON
        run: |
          python scripts/create_binaries_json/create_binaries_json.py \
            --chain_id "${{ inputs.chain_id }}" \
            --tag "${{ inputs.tag }}" \
            --checksums_url "${{ inputs.checksums_url }}" \
            --upgrade_version "${{ inputs.upgrade_version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "feat: add cosmovisor.json for ${{ inputs.tag }}"
          title: "feat: add cosmovisor.json for ${{ inputs.tag }}"
          body: |
            Created cosmovisor.json for ${{ inputs.chain_id }} version ${{ inputs.tag }}

            Using checksums from: ${{ inputs.checksums_url || format('https://github.com/NVNM-Chain/nvnmchain/releases/download/{0}/sha256sum.txt', inputs.tag) }}
          branch: feat/cosmovisor-json-${{ inputs.chain_id }}-${{ inputs.tag }}
          base: main
          draft: true
